### ISSUE TITLE
Add GPU details

### ISSUE THREAD

**Issue by harsha5500** [kthcloud/visualize-frontend#4]
A status of available GPUs may help users to figure out how many GPUs are available before approaching a tier upgrade.

- Add a section that displays Free GPUs.
  - If possible, group by GPU name/type.
- Add which instance/VM is using the available GPUs.

**Comment by pierrelefevre** [comment]
@harsha5500 Are you sure this should be in visualize (projector) and not in https://github.com/kthcloud/console ?

**Comment by harsha5500** [comment]
Console would be better. Projector can stay at how many GPUs are free.
